# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            DysonBlog
tagline:          'Hug Life'
description:      'Hug Life. Personal stuff. Art stuff. Game stuff.'
url:              http://dysonhug.net
baseurl:          /

author:
  name:           'Dyson Hug'
  url:            https://twitter.com/dysonhug

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
